#!/usr/bin/env groovy

pipeline {
    
    agent any

    environment {
        GITHUB_REPO = "git@github.com:YuriyPelykh/NPTT.git"
        GITHUB_CREDENTIAL_ID = "Jenkins_GitHub_Key"
        // DOCKERHUB_CREDENTIAL_ID = ""
    }
    
    stages {
        stage('Pull code from SCM') {
            steps {
                git branch: 'master',
                    credentialsId: "${GITHUB_CREDENTIAL_ID}",
                    url: "${GITHUB_REPO}"
                sh "ls -lah"
            }
        }

        stage('Dockerfiles lint') {
            agent {
                docker {
                    image 'hadolint/hadolint:latest-debian'
                    args '-v ${WORKSPACE}/:/mnt/'
                }
            }
            steps {
                sh 'hadolint /mnt/Dockerfile'
            }
        }

        stage('Containerize App') {
            steps {
                sh 'docker build -t yuriypelykh/ypwp-php-fpm:${BUILD_NUMBER} -t yuriypelykh/ypwp-php-fpm:latest .'
            }
        }

        stage('Push to registry') {
            steps {
                echo "Push"
            }
        }
    }
}
