#!/usr/bin/env groovy

pipeline {
    
    agent any

    parameters {
        string(name: 'IMAGE_TAG', defaultValue: 'latest', description: 'Docker image tag')
    }

    environment {
        GITHUB_REPO = "git@github.com:YuriyPelykh/NPTT.git"
        GITHUB_CREDENTIAL_ID = "Jenkins_GitHub_Key"
        MYSQL_USER_CREDENTIALS = credentials('MySQL_User_Credentials')
        MYSQL_ROOT_CREDENTIALS = credentials('MySQL_Root_Credentials')
        DOCKERHUB_REPO = "yuriypelykh"
        DOCKER_IMAGE_NAME = "ypwp-php-fpm"
        CURRENT_DIR = ""
    }
    
    stages {
        stage('Pull code from SCM') {
            steps {
                git branch: 'master',
                    credentialsId: "${GITHUB_CREDENTIAL_ID}",
                    url: "${GITHUB_REPO}"
                sh "ls -lah"
            }
        }

        stage('Sync app volume') {
            steps {
                echo "${JOB_NAME}"
                script{
                    def CURRENT_DIR = JOB_NAME.toLowerCase(); 
                }
                echo "${CURRENT_DIR}"
                sh "docker run -d --rm --name temp --volume ${CURRENT_DIR}_wp_app:/mnt/ ${DOCKERHUB_REPO}/${DOCKER_IMAGE_NAME}:16 sh -c 'cp -r ./* /mnt/'"
            }
        }
        
        stage('Deploy') {
            steps {
                sh '''MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_CREDENTIALS_PSW} \
                      MYSQL_USER=${MYSQL_USER_CREDENTIALS_USR} \
                      MYSQL_PASSWORD=${MYSQL_USER_CREDENTIALS_PSW} \
                      docker-compose up -d --force-recreate db php-fpm nginx'''
            }
        }
    }
}
